### ISSUE TITLE
Pet taming is broken

### ISSUE THREAD

**Issue by NekoTiga** [DarkflameUniverse/DarkflameServer#125]
Pet taming is broken:
1. Bricks for pet taming are wrong in most of the cases except for Pet Cove pets, they almost never show correct bricks, forcing you to constantly reroll until you get it is showing all of the fitting bricks. 
2. Failing pet taming makes pets stuck with a "correct block" animation above their heads
3. Pet taming for the bone dragon is broken and will say "You have guessed 0 of 7 correct bricks, keep trying!" unless you have guessed it all in one go. Even if at least 1 brick is 100% correct. 
4. Taming screen sometimes zooms in too much, not letting you to see bricks.
![image](https://user-images.githubusercontent.com/20857024/145192629-eefbc38d-5e14-49e8-b339-61c3142d713d.png)
![image](https://user-images.githubusercontent.com/20857024/145193755-7bbfb6ee-ed33-434c-9934-542f5f76d3af.png)

**Comment by NekoTiga** [comment]
![image](https://user-images.githubusercontent.com/20857024/145198469-88bd1be8-f782-447f-9f50-57cc5820ec43.png)

**Comment by averysumner** [comment]
Please provide evidence that the bricks are wrong. They shouldn’t be and I’m unable to reproduce.

**Comment by NealSpellman** [comment]
Agreed on the above. Per your image, I see nothing wrong with the bricks required for the dragon. Sometimes the bricks are hard to guess as they're inside the model rather than a piece on the outside, but it's always possible.

2 is the same issue as #74.

4 is if you're near a wall or object that the camera would clip into, so it moves the camera against it. (like a wall) Please try from a different angle.

**Comment by Mezalion** [comment]
For 3 its not only with the Skeleton but with every Pet i came across thus far

**Comment by averysumner** [comment]
Closing this issue as it is stale and incorporates multiple issues into one. Please open separate issues for each problem that has persisted. It seems only “3” in your description is a valid issue.
