### ISSUE TITLE
Red Ninja Hood - Maelstrom Infused giving too much imagination

### ISSUE THREAD

**Issue by starjones101** [DarkflameUniverse/DarkflameServer#167]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The hat should give you +4 shield +4 imagination as shown in the video but is giving +4 shield and **+8** imagination.

Video: https://streamable.com/xj2dza

### Reproduction steps

/gmadditem 1889 try equipping and unequipping the hat to see that it's giving +8 imagination instead of the shown +4.

### Expected Behavior

It should give you +4 imagination and +4 shield upon equip.

### Environment

Windows Ubuntu

**Comment by Daystar1998** [comment]
Equipping this or other ninja hoods appear to also cause Object 10482 to be equipped. Per the description, 10482 is used to block the neck slot when wearing ninja hoods.

10482 provides the ObjectSkill 372 as a buff. This is what's adding an additional +4 to imagination.

Deleting the 10482 record from the ObjectSkill table in CDServer.sqlite fixes the issue.

**Comment by Xiphoseer** [comment]
> Does anyone know if there is a skill which does nothing but put a blocked symbol or similar in an item slot? Because that would be a better solution than deleting this.

For reference: These are called proxy items, and there's a lot of them: https://explorer.lu/objects/search?query=Proxy
it's not uncommon for them to have skills attached that are supposed to be active. What I find much more likely is the following:

Both 1889 (Red Ninja Hood - Maelstrom Infused) and 10482 (PROXY NINJA HOOD - BACK/NECK PROXY) add the exact same skill 372. So what I assume is wrong is that DLU applies the skills on equip/unequip instead of collecting them into some sort of *active* set and only activating this skill once. Or to put it differently: To disallow duplicate skills and just not apply it if it's already active.

**Comment by EmosewaMC** [comment]
@Xiphoseer I dont think a data structure that stores the skills and activating them once and only once would work.  _Any_ item that gives +4 imagination for example, will use skill 372.  So if the player were to equip both a maelstrom hood _and_ the Zippered Leather Jacket, than the player would only get a net of 4 imagination when they should be getting 8 total.
