### ISSUE TITLE
Piercing Patch Hood attack move not appearing on equip

### ISSUE THREAD

**Issue by starjones101** [DarkflameUniverse/DarkflameServer#168]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The hood has a special spear throw attack which doesn't appear in your hotbar until you launch into the world so the current workaround is doing /testmap <world id>. /die or /kill doesn't seem to work.

Video: https://streamable.com/dzhjwo

### Reproduction steps

/gmadditem 15960. Equip/unequip the hat and see if the move appears in your hotbar, if it doesn't try /testmap <world id>.

### Expected Behavior

The spear throw move appears in your hotbar once the item is equipped.

### Environment

Windows Ubuntu

**Comment by Daystar1998** [comment]
Equipping 15960 also equips the proxy items 15956 and 15957 into the neck slot.

15956: Proxy Ninja Hood with Spear- Back/Neck Proxy
15957: Ninjago Spear on ninja hood Proxy

15956 is the one with the spear skill.
15957 is equipped second and removes the skill as it does not have any skills associated with it.

On login the list of equipped items is added to the character by numerical order of the associated "equipLocation" data in the "ItemComponent" table.
Extra_6 -> 15957
clavicle -> 15956
This causes the skill to be equipped properly.

Per the "ComponentsRegistry" table item 15960 is associated with "component_id" 7364
This bug can be fixed by editing the "subItems" field associated with ItemComponent record id 7364
"15956,15957" -> "15956"

Not sure if editing the CDServer.sqlite like this is the correct solution or if the proxy item equipping order should be reversed. Will need to look at various other items with associated proxy items.

**Comment by Xiphoseer** [comment]
> Not sure if editing the CDServer.sqlite like this is the correct solution or if the proxy item equipping order should be reversed. Will need to look at various other items with associated proxy items.
editing CDClient/CDServer is almost never the *correct* solution and long-term probably also not the easiest.
> Alternatively, the equipping code for proxy items will need to be reworked so they don't remove each other's skills which I believe is the best solution
Yeah, this is what should be done
