### ISSUE TITLE
BUG: Achievements do not always count actions

### ISSUE THREAD

**Issue by CloudyCrayons** [DarkflameUniverse/DarkflameServer#204]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

This is testable with the "Yer Bellyachin' Achivement" in Nimbus Station.

If you purchase exactly as many hot dogs as required you will always be a couple short. I've done this with two characters at this point and they both had this issue. I once did five in a row with the number on the achievements page not changing. _**Relogging fixes this issue.**_

However this does not work on similar achievements like "Dizzy Tikis" in Gnarled Forest. the number of tiki torches I've spun is correct.

Yes I am aware this is probably a low priority bug but it might have larger effects making certain achievements impossible to complete, even with re-logging.

### Reproduction steps

Purchase lots of BBQ blast hot dogs and check the counter to see if the tracker updates when you eat them. 

### Expected Behavior

The counter on the achivements page should update

### Environment

Distributor ID: Ubuntu
Description: Ubuntu 20.04.3 LTS
Release: 20.04
Codename: focal

Mysql: Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

**Comment by Xiphoseer** [comment]
Note: Those two missions mentioned are completely different kinds of "Tasks" internally, specifically
- Mission Task 908 (type 15, Interact) for "Dizzy Tikis"
- Mission Task 386 (type 9, UseItem) for "Quit Yer Bellyachin'"
The way the game works, different systems feed into the mission system and update it. Since you say the server count is correct (it works on reload), this might be an issue with the NotifyMissionTask that we send back to the client.

**Comment by EmosewaMC** [comment]
Just a null ptr issue.  Fixed in #899
