### ISSUE TITLE
BUG: Samurai passive

### ISSUE THREAD

**Issue by Owagadugu** [DarkflameUniverse/DarkflameServer#211]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When you loose all your armor as the samurai the passive that gives you absorption from 15 damage also gives the enemy 15 damage absorption.

### Reproduction steps

Loose all armor as the Samurai

Try to attack enemies.

### Expected Behavior

When my samurai passive was activated it gave me, and the enemies, the passive 15 damage shield as indicated by a white and yellow glow.

### Environment

I was using Ubuntu

**Comment by FutronBob** [comment]
I just played around with a Rank 2 Samurai kit for the first time, and found that this issue is actually **far** more critical than it seems on the surface.

First of all, once the enemies gain the passive invulnerability, no amount of normal player damage will harm them, and they maintain this invulnerability indefinitely.

The ability also activates _every time_ a Samurai without armor is hit, not just when they reach 0 armor, and always affects the enemies around the player.  So every time a Samurai takes damage without armor, it creates a new wave of unkillable enemies.

The worst and most critical part of this though, is that one of these bugged enemies tried to run into the Avant Gardens Sentinel Camp.  Normally the guard would kill him instantly, but even he couldn't kill the glitched enemy, and it resulted in a world crash.

Players could easily exploit this to deliberately crash worlds and/or make all enemies invulnerable.  This needs to be a high priority fix.

**Comment by IAmMajo** [comment]
I think this can be closed because of #339.
