### ISSUE TITLE
Racing smashables have no animation

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#220]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Smashing through things while racing should have a detailed animation. Currently they just fade away.

### Reproduction steps

smash into barrels, cones, etc while racing

### Expected Behavior

there should be an animation of all the bricks flying.

### Environment

ubuntu server

**Comment by MustacheMan2** [comment]
Vehicle crashes also do not have the proper animations, potentially related?

**Comment by EmosewaMC** [comment]
> Vehicle crashes also do not have the proper animations, potentially related?

Yes.  We were not setting the is_smashable flag on serialization of Destructible components correctly.  This caused no smashing animations to be played unless they were explicitly turned on through the LDF key is_smashable.  Turns out the client logical ORs this with the database value...  Sucks that it took so long to find a fix but the game will feel so much more alive with the fix in
