### ISSUE TITLE
DOC: Enhancement 

### ISSUE THREAD

**Issue by leolion3** [DarkflameUniverse/DarkflameServer#227]
### Is your feature request related to a problem?

**I apologize** in advance that the issue uses the "Feature Request" template, the "Documentation Improvement" template returns an error code 400.

Link to my gist: `https://gist.github.com/leolion3/ccf654ab60c8e110c65ef948da6af461`

The documentation is too imprecise in explaining how things are done for simple users.
Even though I and you may agree that if someone has absolutely no experience with the command line they should probably join someone else's server instead of trying to do it themselves, a lot of people still want to do it and head over to discord asking for help.

### Describe the solution you'd like

After helping quite a lot of users on discord with setting up their own servers/clients, here are a couple things in my gist that I would suggest adding:
- Detailed MariaDB Setup, including database user creation, tables creation, granting access to the user to the database and to the `dbo.UNIX_TIMESTAMP` subroutine (required for the leaderboards table as I found out in #202 and access is denied by default)
- A better overview of the resulting build folder structure that needs to be validated
- Better ini file setup
- A perhaps as simple as possible explanation of the different network types (users kept confusing localhost/LAN/WAN setup steps) and what port forwarding and firewall rules need to be set. (Again I agree that if they have no experience they should probably not set up a server, however since they are going to do it anyway we might as well help them)
- Brick-by-Brick building could be fixed by supplying a non-existing Github link, such as my own `leolion3.github.io/404` which returns an error code 404
- Adding a guide to manually update user data in MySQL, and manual name approval
- Assembly animated sign not showing up fix
- Perhaps a "Known Errors" section detailing more user set-up errors and how to deal with them

**Comment by averysumner** [comment]
I still don't believe in spoonfeeding people setup information like this, setting up the server should be for sysadmins and developers.

**Comment by leolion3** [comment]
True, but the more you spoonfeed them the less they spam in the discord chat and the less mentions and DMs me and you get

**Comment by mbramblet** [comment]
While this is true @averysumner, I think you should also consider the specific circumstances of hosting a server.
Namely, hosting publicly is not legal.

If then a local group of friends, or even just one person, wants to host a server, but none are code savvy, the process becomes much more difficult, and they'll need to try and get help from someone more qualified.

Adding easy "spoonfeeding" steps means more people can play without relying on a coder being present.

In any case, it certainly won't hurt to supply simpler steps to those who need them.
Who knows, this may be the first coding-based experience that sparks a future career or passion.

**Comment by Xiphoseer** [comment]
Personally, I'm not a fan of the "code-savy" distinction when in relation to ease of use. That's because even with years of experience, a badly documented setup can be really hard because it might be a tiny problem that blocks every step after it. The biggest advantage "coders" have is that they know which assumptions they have about the setup process and can test whether those holf and then adapt or file a bug report.

As for this specific issue: I think improved documentation is great. So I'm open to the idea of merging a PR based on this tutorial into sth like a `guides` subfolder. If you want to submit one such PR, we can do a proper review and provide some feedback. A few notes upfront:

- This tutorial assumes Windows + WSL, so parts of it generalize to Windows and parts of it generalize to linux setups. It'd be nice to split those up so people are less likely to try this in other combinations (eg calling nano in powershell)
- From my point of view, this tutorial has some very opinionated ways of dealing with pulling updates. I don't think we'd merge those in the same go as some of the more basic steps
- You could maybe suggest using https://fdb.lu-dev.net and/or https://lu-dev.net/LUnpack for some steps now
- The guide pulls in a list of English words as a white list from a third party. We don't allow relaxed white lists in this repo, so that would need to go
