### ISSUE TITLE
ENH: Fix double storage in LootGenerator

### ISSUE THREAD

**Issue by codeshaunted** [DarkflameUniverse/DarkflameServer#274]
### Is your feature request related to a problem?

LootGenerator caches quite a bit of data on startup leading to significantly more memory usage on the WorldServer.

### Describe the solution you'd like

Possibly use references to the existing tables in memory to reduce this memory usage.

**Comment by TurtleTheSeaHobo** [comment]
I wanted to a try and contribute a bit to this repo, so I've started working on this issue to build some familiarity.

Looking at the code for `LootGenerator`, a lot of the caching is happening because of either: a) no mapping existing between two properties in the existing `CDTable`s, or (more commonly) b) the need to iterate through every table entry with a certain ID (for instance, `CDLootMatrix` objects in `CDLootMatrixTable` are actually the individual entries into various loot matrices, which `LootGenerator` collects and groups into actual `LootMatrix` objects when it's caching).

If we replace every cache struct with a pointer to the data it copied from the various `CDTable`s, we could save some substantial memory---assuming 8-byte pointers, around 12 bytes for every cached `LootMatrixEntry` (currently 20 bytes), though `RarityTableEntry` and `LootTableEntry` would stay the same size. So that route is certainly viable.

Depending on how much the `CDTable`s are actually used in normal, post-startup operation, it might actually make more sense to rework them to be destroyed after startup (i.e. once everyone's finished caching from them and such). As it stands, they're effectively caches themselves of the various tables in the `CDClientDatabase`. If that database is constant at runtime and certain tables aren't being accessed after startup, we could probably just destroy them and get their space back.

If one of the regular devs wants to give their insight, I'm all ears. I'm gonna start experimenting.

**Comment by TurtleTheSeaHobo** [comment]
Never mind what I said earlier about reworking `CDTable`s. Upon further investigation, it looks like they are needed post-startup pretty significantly. I do think, however, it might be possible to get the `RollLootMatrix` methods and similar to not depend on the caches.

**Comment by TurtleTheSeaHobo** [comment]
After working on this for a while, I think the best solution (and the one I have in my fork) is to remove caching entirely. The type of caching seems not to be used very prevalently elsewhere in the codebase and there seems be no qualms with querying tables all the time.

I haven't noticed any significant change in overall performance with this solution, as it seems `LootGenerator` isn't incredibly performance-critical. The memory profile of `LootGenerator`, however, drops to zero with this approach, since all of its members were those caches and it includes no other static data.

Additionally, by caching that data from the tables on initialization and never again, an incoherency exists whereby a potential update to the loot tables is not reflected in `LootGenerator`. At the very least, it's good to resolve this indirection, even if the `CDTable`s will always remain static.

I'm testing my fork a bit more thoroughly before I make a PR. Nothing I modified should change loot behavior or cause exceptions, but I'd like to be sure.

**Comment by averysumner** [comment]
> there seems be no qualms with querying tables all the time

I think this should change.

**Comment by TurtleTheSeaHobo** [comment]
Probably. I severely underestimated the performance impact of my PR at scales beyond 10 or so players. There's probably some performance to be gained if that can be rectified.

I believe making caching a more widespread practice is a bad idea. It seems indicative of a more general problem with how this data is stored/accessed. Maybe processing the tables into more efficiently accessed structures at init time? 

For instance, if we had an object that collected `CDLootTableTable` into `LootTable`s with vectors of `LootTableEntry`s before destroying `CDLootTableTable`, we could have the data stored in one place with the two classes that need it, `LootGenerator` and `VendorComponent`, sharing.
