### ISSUE TITLE
BUG: Flags for tutorials are never set causing them to be repeated

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/DarkflameServer#395]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When the player enters a specific area for the first time, a tutorial plays telling the player useful controls, however on the server these flags are never properly set and as such these tutorials repeat every time you get to these areas.

### Reproduction steps

1) Enter for example, Gnarled Forests bridge area and observe the right mouse tutorial.
2) leave the area and come back to the bridge
3) tutorial repeats

### Expected Behavior

Tutorial happens only once.

### Environment

Ubuntu

**Comment by MustacheMan2** [comment]
As annoying as it is, this is live accurate.

visit 1: https://youtu.be/5OrRMmr4aUU?t=230
visit 2: https://youtu.be/mk6qNOzs4dw?t=154

**Comment by EmosewaMC** [comment]
Well then it's a live bug that can be fixed.  There are flags to mark these tutorials as seen in the database.

**Comment by cooltrain7** [comment]
> Well then it's a live bug that can be fixed. There are flags to mark these tutorials as seen in the database.

Coincidence you posted this issue - I actually looked into this today.

I don't *think* its as simple as that, atleast from what I've seen. In AG before the monument there is the spot where it wants you to build a half bridge, this area has the trigger volume that will fire for flag `27`, the double jump hint.

The issue with it is its fired by `GameMessages::HandleSetFlag` which comes straight from the client. On top of that (atleast for `27` and I suspect the others too) it fires twice. 

```
[HandleSetFlag] Update Flag 27 - From 0 to 0
[HandleSetFlag] Update Flag 27 - From 1 to 1
```

For whatever reason the flag is set to false when you enter the volume, and then true again once you complete the action. It also seems like that flag just is flatout not saving. Otherwise I would expect that first value to be from 1 to 0.

**Comment by EmosewaMC** [comment]
Did some tests and the only way to fix this from my testing is to do so from the client side in the .lua files that control tutorials.  Closing this since its no longer a DLU bug and is now a separate client bug.

**Comment by cooltrain7** [comment]
> Did some tests and the only way to fix this from my testing is to do so from the client side in the .lua files that control tutorials.

I figured as much, good to know someone else tested it too.
