### ISSUE TITLE
BUG: Level reward pop-ups don't appear

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#401]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When you reach level 10, 20, etc, nothing displays, only the item rewards going into your backpack.

### Reproduction steps

Level up to 5, 10, 15, 20, 25, 30, 35, 40, or 45. You'll see the item reward go to your inventory.

### Expected Behavior

There should be an achievement pop-up displaying "You are now Level 5" or similar
![Capture](https://user-images.githubusercontent.com/48499798/150458564-5c042412-f8fe-4346-b832-d768edac24e6.PNG)
.

### Environment

ubuntu server

**Comment by EmosewaMC** [comment]
Some video of whats supposed to happen as well:
https://youtu.be/MqCXe_Lo9rg?t=5088

**Comment by Jettford** [comment]
If there is a Level 5 pop up, there is likely packet captures of this as I am pretty sure one of the characters Pwjones used when capturing was a new FTP character.

**Comment by Xiphoseer** [comment]
Because the screenshot is level 5, the video level 35, both are nice, round numbers and happen to be in the https://explorer.lu/misc/level-rewards table - and in the video it even turns around to show that reward, I assume this is just a simple case of this function
https://github.com/DarkflameUniverse/DarkflameServer/blob/13980c4133a45e1d2c0c8a37e72970296caac11c/dGame/dComponents/CharacterComponent.cpp#L189
not sending
https://lcdruniverse.org/lu_packets/lu_packets/world/gm/client/struct.NotifyLevelRewards.html
