### ISSUE TITLE
BUG: AGS Buff Stations still don't spawn powerups

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#422]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The powerups make the sound effect and show the particle effect but nothing actually drops.

### Reproduction steps

build a buff station and wait

### Expected Behavior

the stations should spawn powerups.

### Environment

ubuntu server

**Comment by NealSpellman** [comment]
This is expected behavior from the #397; looks like there's a script for the Buff Station that gives you 1 of each stat while you're in its' radius every 2.5s.

I know at some point in Live it dropped powerups, but does anyone have footage from the end of Live that included this? I wonder if it got patched at some point and stopped dropping powerups or if this was the "original" behavior before powerups dropped from it.

**Comment by Marcono1234** [comment]
In [this video by jamessterV2](https://youtu.be/iWe3KZv2TJE?t=92) recorded on November 5, 2011 (according to the description), and therefore after the last patch (?), it looks like multiple powerups have accumulated on top of the buff station.

**Comment by NealSpellman** [comment]
Thanks for the video, looks like @EmosewaMC was wrong about the script being the last Live behavior. Marking this low priority since it's not a huge deal and the buff station at least is doing _something_ right now.

**Comment by EmosewaMC** [comment]
ill get to this in a bit - I based my claims on the behavior for spawning powerups not existing and then realized there is no behavior for spawning powerups so of course that wouldn't be on the entity page.  I don't know exactly how the spawned powerup works, but it looks to just be a random one.
