### ISSUE TITLE
BUG: Completed Quick Builds do not "Jump"

### ISSUE THREAD

**Issue by BrieFlory** [DarkflameUniverse/DarkflameServer#446]
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Completed quick builds are supposed to visually jump up and land back in place upon completion, mimicking the behavior seen in Tt LEGO games.

Countless examples can be found in videos from Live, but here's just one:

https://youtu.be/5OrRMmr4aUU?t=478

Notice how the Pirate Archway does a little bounce. Looking through the videos, this seems to occur with all quick builds.

### Reproduction steps

1) Walk up to quick build
2) Hold SHIFT to build object
3) When quick build completes, note lack of jump.

### Expected Behavior

The completed build should do a little "jump" before landing in place.

### Environment

Win11, i7-9700k, RTX 2070 Super, 32GB DDR4 RAM

**Comment by averysumner** [comment]
Odd that no one else has ever noticed this… possibly some GM that needs to be sent on complete? Quickbuilds have a lot of hardcoded GMs (see the head glow).

**Comment by Terrev** [comment]
May be worth noting that, going by happy flower, quickbuilds can be configured to skip this, but I'm not aware of any that actually do so off the top of my head

**Comment by EmosewaMC** [comment]
So ive figured out the issue here.  The issue was when we serialized the quickbuild on completion, we were serializing it without a builder.  
![image](https://user-images.githubusercontent.com/39972741/166391999-b3c3fea7-46d7-433b-856d-ec3d7a41a2e5.png)
The packet caps from live show that, when completed, we are supposed to serialize the builder ID even if they are done building.  Will put in a PR soon after more testing
