### ISSUE TITLE
MasterServer unable to connect to localhost

### ISSUE THREAD

**Issue by padraicheaton** [DarkflameUniverse/DarkflameServer#89]
I've fixed this now by redoing all the steps using the WSL for windows rather than just raw windows, and it seems to have worked fine! Running into another issue now:

"[07-12-21 23:36:38] [MasterServer]: Got an error while connecting to the database: Unable to connect to localhost"

have tried going through everything in the issues here, but I can't find a solution. I'm running the mysql database locally on my computer, same as the server with each .ini file configured as:

mysql_host=localhost
mysql_database=lu_database
mysql_username=root
mysql_password=*******

_Originally posted by @padraicheaton in https://github.com/DarkflameUniverse/DarkflameServer/issues/19#issuecomment-987888714_

**Comment by Landshark77** [comment]
what do you have set for your external_ip setting in the three ini files?  Should be set to the machine IP and not localhost.

**Comment by padraicheaton** [comment]
I've got the external_ip set to being my exernal ip (just found it by doing ifconfig) I also tried using the addresses found by doing 'ipconfig' just in a normal windows terminal, and no dice.

**Comment by Landshark77** [comment]
Two other possible solutions here: https://github.com/DarkflameUniverse/DarkflameServer/issues/25#issue-1071673339

**Comment by padraicheaton** [comment]
I'm running the MariaDB on windows, so I added that line to my C:/Program Files/MariaDB 10.6/data/my.ini (which already had the header '[mysqld]' so I reckon it was the windows equivalent]. Would that be an issue? Running the MariaDB on windows and then trying to run the server on WSL?

**Comment by piersonjon** [comment]
I was unable to solve the issue, although I think it may have been related to using a WSL2 instance (see #43).

I was able to get the database element to resolve, however, by installing MySQL into WSL:

sudo apt install mysql-server
sudo /etc/init.d/mysql start
sudo mysql
CREATE DATABASE <dbname>;
CREATE USER '<username'@'localhost' WITH PASSWORD <pwd>;
GRANT ALL  PRIVILEGES ON <dbname>.* TO '<username'@'localhost';

From here, I used DBVisualizer Free to populate the script since I'm not aware off the top of my head on how to run the SQL file to create the tables.

**Comment by padraicheaton** [comment]
followed everything in this vid, helped a ton and got this fixed

https://www.youtube.com/watch?v=mDGoV5AYaDo&t=1032s
